### ISSUE TITLE
Tweets rendering only as text

### ISSUE THREAD

**Issue by DrewArnold1** [gadenbuie/tweetrmd#12]
Over the past few days, tweets have been rendering only as plain text.  See example tweets in the readme of this repository.  Are others seeing this, too?

**Comment by aravind-j** [comment]
Yes it seems that `hide_media = FALSE` is being ignored.

**Comment by gadenbuie** [comment]
Probably relevant (at least in terms of motivation to invest time in this):

> Starting February 9, we will no longer support free access to the Twitter API, both v2 and v1.1. A paid basic tier will be available instead 🧵
> 
> https://twitter.com/twitterdev/status/1621026986784337922

**Comment by gadenbuie** [comment]
good news, I think I've fixed this by updating the bundled twitter widgets javascript in eb8424beba0f783580ca397abbe8b1d1a6375ad4
