### ISSUE TITLE
Set Timezone for screenshots.

### ISSUE THREAD

**Issue by simonheb** [gadenbuie/tweetrmd#3]
I am taking screenshots from a PC set to GMT. The tweets in my screenshot use this timezone to display when they were posted. I need this to be shown as UTC. Is there a way to take screenshots as if I was in UTC?

**Comment by gadenbuie** [comment]
I'm sorry, I clearly see the need but don't think this will be easy for me to handle in `tweetrmd`. This package is a small wrapper (to orchestrate tweet screeshots) around [webshot2](https://github.com/rstudio/webshot2) which is itself a small wrapper (to orchestrate web screenshots) around [chromote](https://github.com/rstudio/chromote) (headless chrome sessions).

With a little poking around, it seems that it may be possible to request that the headless chrome session emulate a particular time zone with [Emulation.setTimezoneOverride](https://chromedevtools.github.io/devtools-protocol/tot/Emulation/#method-setTimezoneOverride). But this method isn't exposed in chromote and certainly isn't accessible via webshot2.

Is it possible (or would it be easier) to change your system time (a terrible suggestion, I know)?

**Comment by simonheb** [comment]
> 
> 
> I'm sorry, I clearly see the need but don't think this will be easy for me to handle in `tweetrmd`. This package is a small wrapper (to orchestrate tweet screeshots) around [webshot2](https://github.com/rstudio/webshot2) which is itself a small wrapper (to orchestrate web screenshots) around [chromote](https://github.com/rstudio/chromote) (headless chrome sessions).
> 
> With a little poking around, it seems that it may be possible to request that the headless chrome session emulate a particular time zone with [Emulation.setTimezoneOverride](https://chromedevtools.github.io/devtools-protocol/tot/Emulation/#method-setTimezoneOverride). But this method isn't exposed in chromote and certainly isn't accessible via webshot2.
> 
> Is it possible (or would it be easier) to change your system time (a terrible suggestion, I know)?

Ok, fair. This is for a twitter bot that needs to run 24/7 anyways, so sooner or later it'll get a tiny server to run from anyways, then this will work.
